#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - pip
            script:
              - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              - pip install pytest
              #- pytest -v tests/* --junitxml=test-reports/report.xml
        - step:
            name: Lint code
            script:
              # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
              - pip install flake8
              #- flake8 . --extend-exclude=dist,build --show-source --statistics
- pipe: atlassian/heroku-deploy:1.2.1
  variables:
    HEROKU_API_KEY: '17559a0e-d16d-4943-8875-e391e1b164c9'
    HEROKU_APP_NAME: 'raid-organizer'
    ZIP_FILE: 'heroku.zip'
    # WAIT: '<boolean>' # Optional.
    # DEBUG: '<boolean>' # Optional