#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - pip
            script:
              - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              - pip install pytest
              - git archive --format=tar.gz devel -o organizer-app.tar.gz
              #- pytest -v tests/* --junitxml=test-reports/report.xml
            artifacts:
              - courier-app.tar.gz
        - step:
            name: Lint code
            script:
              # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
              - pip install flake8
              #- flake8 . --extend-exclude=dist,build --show-source --statistics
              - pipe: atlassian/heroku-deploy:1.2.1
                variables:
                  HEROKU_API_KEY: $HEROKU_API_KEY
                  HEROKU_APP_NAME: $HEROKU_APP_NAME
                  ZIP_FILE: organizer-app.tar.gz
